ostrk/cart/urls.py
from django.urls import path

from cart import views

app_name = 'cart'

urlpatterns = [
    path('add/<product_id>/', views.add_to_cart, name='add_to_cart'),
    path('remove/<product_id>/', views.remove_from_cart, name='remove_from_cart'),
    path('list/', views.show_cart, name='show_cart'),
]

ostrk/orders/urls.py
from django.urls import path

from orders import views

app_name = "orders"

urlpatterns = [
    path('create', views.create_order, name='create_order'),
    path('list', views.user_orders, name='user_orders'),
    path('checkout/<int:order_id>', views.checkout, name='checkout'),
    path('fake-payment/<int:order_id>', views.fake_payment, name='pay_order')
]

ostrk/ostrk/urls.py
from django.contrib import admin
from django.urls import path, include
from women import views
from women.views import page_not_found

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('women.urls')),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('cart/', include('cart.urls', namespace='cart')),
    path('orders/', include('orders.urls', namespace='orders')),
]

handler404 = page_not_found

ostrk/cart/models.py
from django.db import models

# Create your models here.

ostrk/cart/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.contrib import messages
from django.contrib.auth.decorators import login_required

from cart.utils.cart import Cart
from women.forms import QuantityForm
from women.models import Product


@login_required
def add_to_cart(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    form = QuantityForm(request.POST)
    if form.is_valid():
        data = form.cleaned_data
        cart.add(product=product, quantity=data['quantity'])
        messages.success(request, 'Added to your cart!', 'info')
    return redirect('women:product_detail', slug=product.slug)


@login_required
def show_cart(request):
    cart = Cart(request)
    context = {'title': 'Cart', 'cart': cart}
    return render(request, 'cart.html', context)


@login_required
def remove_from_cart(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    cart.remove(product)
    return redirect('cart:show_cart')

ostrk/cart/templates/cart.html
{% extends "base.html" %}

{% block content %}
<div class="col-md-2"></div>
{% if cart_count != 0 %}
<div class="col-md-8 border rounded p-3">
<table class="table table-striped ">
    <thead class="text-muted">
      <tr>
        <th scope="col"></th>
        <th scope="col">Товар</th>
        <th scope="col">Цена за шт.</th>
        <th scope="col">Кол-во</th>
        <th scope="col">Сумма</th>
        <th scope="col"></th>
      </tr>
    </thead>
    {% for item in cart %}
    <tbody>
      <tr>
        <th scope="row">{{ forloop.counter }}</th>
        <td><a class="text-decoration-none" href="{{ item.product.get_absolute_url }}">{{ item.product.title }}</a></td>
        <td>${{ item.price }}</td>
        <td>{{ item.quantity }}</td>
        <td>${{ item.total_price }}</td>
        <td><a class="text-danger text-decoration-none" href="{% url 'cart:remove_from_cart' item.product.id %}">Удалить</a></td>
      </tr>
    </tbody>
    {% endfor %}
</table>
<hr>
<a href="{% url 'orders:create_order' %}" style="float: right;" class="btn btn-success mt-1">Подтвердить</a>
<h4 class="mt-4"><span class="text-muted">Сумма:</span> ₽{{ cart.get_total_price }}</h4>
</div>
{% else %}
<div class="col-md-8 mt-5 pt-5 text-center">
  <br>
  <h3 class="text-muted text-capitalize">Корзина пуста..!</h3>
  <a href="/" class="text-primary text-decoration-none">Назад</a>
</div>
{% endif %}
<div class="col-md-2"></div>

{% endblock %}