ostrk/cart/urls.py
from django.urls import path

from cart import views

app_name = 'cart'

urlpatterns = [
    path('add/<product_id>/', views.add_to_cart, name='add_to_cart'),
    path('remove/<product_id>/', views.remove_from_cart, name='remove_from_cart'),
    path('list/', views.show_cart, name='show_cart'),
]

ostrk/ostrk/urls.py
from django.contrib import admin
from django.urls import path, include
from women import views
from women.views import page_not_found

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('women.urls')),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('cart/', include('cart.urls', namespace='cart')),
    path('orders/', include('orders.urls', namespace='orders')),
]

handler404 = page_not_found

ostrk/women/urls.py
from django.conf.urls.static import static
from django.urls import path

from ostrk import settings
from . import views

app_name = 'women'

urlpatterns = [
    path('', views.index, name='index'),
    path('cats/<int:cat_id>', views.categories, name='cats'),
    path('about/', views.about, name='about'),
    path('category/<slug:slug>/', views.category, name='category'),
    path('<slug:slug>', views.product_detail, name='product_detail'),
    path('filter/<slug:slug>/', views.filter_by_category, name='filter_by_category'),
    path('favorites/', views.favorites, name='favorites'),
    path('add/favorites/<int:product_id>/', views.add_to_favorites, name='add_to_favorites'),
    path('remove/favorites/<int:product_id>/', views.remove_from_favorites, name='remove_from_favorites'),
    path('search/', views.search, name='search'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

ostrk/women/models.py
from django.db import models
from django.template.defaultfilters import slugify
from django.urls import reverse


# Create your models here.

class Category(models.Model):
    title = models.CharField(max_length=100)
    sub_category = models.ForeignKey(
        'self', on_delete=models.CASCADE,
        related_name='sub_categories', blank=True, null=True
    )
    is_sub = models.BooleanField(default=False)
    slug = models.SlugField(max_length=255, unique=True, db_index=True, verbose_name="URL")

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('women:category', kwargs={'slug': self.slug})

    def save(self, *args, **kwargs):
        return super().save(*args, **kwargs)


class Product(models.Model):
    category = models.ForeignKey(Category, on_delete=models.CASCADE, related_name='category')
    image = models.ImageField(upload_to='products')
    title = models.CharField(max_length=250)
    description = models.TextField()
    price = models.IntegerField()
    date_created = models.DateTimeField(auto_now_add=True)
    slug = models.SlugField(unique=True)

    class Meta:
        ordering = ('-date_created',)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('women:product_detail', kwargs={'slug': self.slug})

    def save(self, *args, **kwargs):
        return super().save(*args, **kwargs)

ostrk/women/forms.py
from django import forms


class QuantityForm(forms.Form):
    quantity = forms.IntegerField(label='',
        min_value=1, max_value=9, widget=forms.NumberInput(
            attrs={'class': 'form-control mt-1','placeholder': 'quantity'}
        )
    )

ostrk/women/views.py
from itertools import product

from django.http import HttpResponse, HttpResponseNotFound
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from django.core.paginator import Paginator
from django.template.loader import render_to_string

from women.forms import QuantityForm
from women.models import Category, Product


# Create your views here.
def index(request):
    catalog = Category.objects.all()
    data = {
        'titile': 'Главная страница',
        'catalog': catalog,
    }
    return render(request, 'women/index.html', data)


def about(request):
    return render(request, 'women/about.html', {'title': 'О нас'})


def categories(request, cat_id):
    return HttpResponse("Hello, world. You're at the polls categories.")


def page_not_found(request, exception):
    return HttpResponseNotFound('Страница не найдена')


def category(request, slug):
    product = get_object_or_404(Category, slug=slug)
    related_products = Product.objects.filter(category_id=product.sub_category_id).all()[:5]
    context = {
        'title': product.title,
        'product': product,
        'favorites': 'favorites',
        'related_products': related_products
    }
    return render(request, 'women/catalog.html', context)


def product_detail(request, slug):
    form = QuantityForm()
    product = get_object_or_404(Product, slug=slug)
    related_products = Product.objects.filter(category=product.category).all()[:5]
    context = {
        'title': product.title,
        'product': product,
        'form': form,
        'favorites': 'favorites',
        'related_products': related_products
    }
    return render(request, 'women/cat_detail.html', context)


@login_required
def add_to_favorites(request, product_id):
    product = get_object_or_404(Product, id=product_id)
    request.user.likes.add(product)
    return redirect('women:product_detail', slug=product.slug)


@login_required
def remove_from_favorites(request, product_id):
    product = get_object_or_404(Product, id=product_id)
    request.user.likes.remove(product)
    return redirect('women:favorites')


@login_required
def favorites(request):
    products = request.user.likes.all()
    context = {'title': 'Favorites', 'products': products}
    return render(request, 'women/favorites.html', context)

def search(request):
    query = request.GET.get('q')
    products = Product.objects.filter(title__icontains=query).all()
    context = {'products': paginat(request, products)}
    return render(request, 'women/index.html', context)

def filter_by_category(request, slug):
    """when user clicks on parent category
    we want to show all products in its sub-categories too
    """
    result = []
    category = Category.objects.filter(slug=slug).first()
    [result.append(product) for product in Product.objects.filter(category=category.id).all()]
    # check if category is parent then get all sub-categories
    if not category.is_sub:
        sub_categories = category.sub_categories.all()
        # get all sub-categories products
        for category in sub_categories:
            [result.append(product)
             for product in Product.objects.filter(category=category).all()]
    context = {'products': paginat(request, result)}
    return render(request, 'women:index', context)

ostrk/women/templates/women/about.html
{% extends 'base.html' %}

{% block content %}

<div class="container text-center">
  <div class="row">
    <div class="col">
      1 of 3
    </div>
    <div class="col-6">
      2 of 3 (шире)
    </div>
    <div class="col">
      3 of 3
    </div>
  </div>
  <div class="row">
    <div class="col">
      1 of 3
    </div>
    <div class="col-5">
      2 of 3 (шире)
    </div>
    <div class="col">
      3 of 3
    </div>
  </div>
</div>
{% endblock %}

ostrk/women/templates/women/cat_detail.html
{% extends 'base.html' %}

{% block content %}
<div class="container text-center">
    <div class="row mb-3 mt-4">
        <div class="col-md-1"></div>
        <!-- product content -->
        <div class="col-md-5 p-3 border rounded">
            <!-- category -->
            <div class="border-bottom mb-2 pb-2">
                <span class="text-muted ">Категория:</span><a class="text-decoration-none text-dark"
                                                               href="{% url 'women:filter_by_category' product.category.slug %}">
                {{product.category}}</a>
            </div>
            <!-- title -->
            <h2>{{ product.title }}</h2>
            <!-- price -->
            <h4 class="mt-4 text-dark">Price: ${{ product.price }}</h4>
            <!-- description -->
            <div class="mt-4 pe-3 mb-5">{{ product.description }}</div>
            <!-- cart btn -->
            <form method="post" action="{% url 'cart:add_to_cart' product.id %}">
                {% csrf_token %}
                {{ form }}
                <input type="submit" class="btn btn-primary mt-4" value="Add to cart">
            </form>
            <br>
            {% if favorites == 'remove' %}
            <a href="{% url 'women:remove_from_favorites' product.id %}"
               class="btn btn-outline-danger mt-5 text-capitalize ">{{favorites}} from favorites</a>
            {% else %}
            <a href="{% url 'women:add_to_favorites' product.id %}"
               class="btn btn-outline-success mt-5 text-capitalize ">add to {{favorites}}</a>
            {% endif %}
        </div>
        <!-- product image -->
        <div class="col-md-6">
            <img style="object-fit: cover;" class="rounded" src="{{ product.image.url }}" width="510" height="500">
        </div>
    </div>
    <!-- related products -->
    <div class="row mt-4 mb-4">
        <h3>Related Products:</h3>
        <hr>
        {% for p in related_products %}
        <!-- dont show the current product in this page -->
        {% if p != product %}
        <div class="card me-2 mb-2" style="width: 16rem;">
            <img style="object-fit: cover;" class="card-img mt-2" width="268" height="200" src="{{ p.image.url }}">
            <div class="mt-3 text-center">
                <h5 class="card-title">{{ p.title }}</h5>
                <p class="text-muted">${{ p.price }}</p>
                <a href="{{ p.get_absolute_url }}" class="mb-3 btn btn-outline-primary w-100">Buy Now</a>
            </div>
        </div>
        {% endif %}
        {% endfor %}
    </div>
</div>
{% endblock %}

ostrk/women/templates/women/catalog.html
{% extends 'base.html' %}

{% block content %}
<div class="container text-center">
    <div class="row mt-4 mb-4">
        <h3>Доступные товары:</h3>
        <hr>
        {% for p in related_products %}
        <!-- dont show the current product in this page -->
        <div class="card me-2 mb-2" style="width: 16rem;">
            <img style="object-fit: cover;" class="card-img mt-2" width="268" height="200" src="{{ p.image.url }}">
            <div class="mt-3 text-center">
                <h5 class="card-title">{{ p.title }}</h5>
                <p class="text-muted">${{ p.price }}</p>
                <a href="{{ p.get_absolute_url }}" class="mb-3 btn btn-outline-primary w-100">Купить</a>
            </div>
        </div>
        {% endfor %}
    </div>
</div>
{% endblock %}

ostrk/women/templates/women/favorites.html
{% extends 'base.html' %}
{% block content %}
{% if products %}
<h2>Your Favorites</h2>
<hr>
{% for product in products %}
<div class="card me-2 mb-2" style="width: 16rem;">
  <img style="object-fit: cover;" class="card-img mt-2" width="268" height="200" src="{{ product.image.url }}">
  <div class="mt-3 text-center">
    <h5 class="card-title">{{ product.title }}</h5>
    <p class="text-muted">${{ product.price }}</p>
    <a href="{{ product.get_absolute_url }}" class="mb-3 btn btn-primary w-100">Купить</a>
  </div>
  <a href="{% url 'women:remove_from_favorites' product.id %}" class="mb-3 btn btn-outline-danger">Удалить</a>
</div>
{% endfor %}
{% else %}
<div class="row">
  <div class="col-md-2"></div>
  <div class="col-md-8 mt-5 pt-5 text-center">
    <br>
    <h3 class="text-muted text-capitalize">favorites list is empty..!</h3>
    <a href="/" class="text-primary text-decoration-none">Назад</a>
  </div>
  <div class="col-md-2"></div>
</div>
{% endif %}
{% endblock %}

ostrk/women/templates/women/index.html
{% extends 'base.html' %}

{% block content %}
<div class="container">
    <div id="carouselExampleSlidesOnly" class="carousel slide" data-bs-ride="carousel">
        <div class="carousel-inner">
            <div class="carousel-item active">
                <img src="https://avatars.mds.yandex.net/i?id=f9b6ba04b5235bf11f824961a2543365_l-3949311-images-thumbs&n=13"
                     class="d-block w-100" alt="...">
            </div>
            <div class="carousel-item">
                <img src="https://4trak.ru/wp-content/uploads/2023/01/zapchasti-dlja-minitraktorov.jpg"
                     class="d-block w-100" alt="...">
            </div>
            <div class="carousel-item">
                <img src="https://spectehzapchast.ru/uploads/s/b/x/q/bxqa5gbjquzl/img/full_aeenJ2dB.png"
                     class="d-block w-100" alt="...">
            </div>
        </div>
    </div>
</div>
<div class="container text-center">
    <div class="row">
        <div class="col-md-6 mb-3">
            <img class="w-100"
                 src="https://avatars.mds.yandex.net/i?id=06a88de0467c444e76eb9d72f69c1e55_l-5241497-images-thumbs&n=13"
                 alt="">
            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Alias beatae doloribus ex iusto suscipit,
                tempora voluptas. Odit quas quisquam sapiente?</p>
        </div>
        <div class="col-md-6 mb-3">
            <img class="w-100"
                 src="https://avatars.mds.yandex.net/i?id=06a88de0467c444e76eb9d72f69c1e55_l-5241497-images-thumbs&n=13"
                 alt="">
            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Est inventore iste quaerat quia totam. Aliquam
                corporis dolorem eius eum excepturi exercitationem perferendis quod quos saepe.</p>
        </div>
    </div>
    <div class="row">
        <div class="col mb-3">
            <div class="card" style="width: 18rem;">
                <img class="w-100"
                     src="https://avatars.mds.yandex.net/i?id=06a88de0467c444e76eb9d72f69c1e55_l-5241497-images-thumbs&n=13"
                     class="card-img-top" alt="...">
                <div class="card-body">
                    <h5 class="card-title">Заголовок карточки</h5>
                    <p class="card-text">Небольшой пример текста, который должен основываться на названии карточки и
                        составлять основную часть содержимого карты.</p>
                    <a href="#" class="btn btn-primary">Перейти куда-нибудь</a>
                </div>
            </div>
        </div>
        <div class="col mb-3">
            <div class="card" style="width: 18rem;">
                <img class="w-100"
                     src="https://avatars.mds.yandex.net/i?id=06a88de0467c444e76eb9d72f69c1e55_l-5241497-images-thumbs&n=13"
                     class="card-img-top" alt="...">
                <div class="card-body">
                    <h5 class="card-title">Заголовок карточки</h5>
                    <p class="card-text">Небольшой пример текста, который должен основываться на названии карточки и
                        составлять основную часть содержимого карты.</p>
                    <a href="#" class="btn btn-primary">Перейти куда-нибудь</a>
                </div>
            </div>
        </div>
        <div class="col mb-3">
            <div class="card" style="width: 18rem;">
                <img class="w-100"
                     src="https://avatars.mds.yandex.net/i?id=06a88de0467c444e76eb9d72f69c1e55_l-5241497-images-thumbs&n=13"
                     class="card-img-top" alt="...">
                <div class="card-body">
                    <h5 class="card-title">Заголовок карточки</h5>
                    <p class="card-text">Небольшой пример текста, который должен основываться на названии карточки и
                        составлять основную часть содержимого карты.</p>
                    <a href="#" class="btn btn-primary">Перейти куда-нибудь</a>
                </div>
            </div>
        </div>
        <div class="col mb-3">
            <div class="card" style="width: 18rem;">
                <img class="w-100"
                     src="https://avatars.mds.yandex.net/i?id=06a88de0467c444e76eb9d72f69c1e55_l-5241497-images-thumbs&n=13"
                     class="card-img-top" alt="...">
                <div class="card-body">
                    <h5 class="card-title">Заголовок карточки</h5>
                    <p class="card-text">Небольшой пример текста, который должен основываться на названии карточки и
                        составлять основную часть содержимого карты.</p>
                    <a href="#" class="btn btn-primary">Перейти куда-нибудь</a>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock %}