ostrk/accounts/urls.py
from django.urls import path, reverse_lazy
from django.contrib.auth import views as auth_views

from accounts import views


app_name = 'accounts'

urlpatterns = [
    path('register/', views.user_register, name='user_register'),
    path('login/', views.user_login, name='user_login'),
    path('login/manager/', views.manager_login, name='manager_login'),
    path('logout/', views.user_logout, name='user_logout'),
    path('profile/edit', views.edit_profile, name='edit_profile'),
    path(
        'password-reset/',
        auth_views.PasswordResetView.as_view(
            template_name='password_reset.html',
            success_url=reverse_lazy('accounts:password_reset_done'),
            email_template_name='email_template.html'
        ),
        name='password_reset'
    ),
    path(
        'password-reset/done',
        auth_views.PasswordResetDoneView.as_view(
            template_name='password_reset_done.html',
        ),
        name='password_reset_done'
    ),
    path(
        'password-reset-confirm/<uidb64>/<token>/',
        auth_views.PasswordResetConfirmView.as_view(
            template_name='password_reset_confirm.html',
            success_url=reverse_lazy('accounts:password_reset_complete'),
        ),
        name='password_reset_confirm'
    ),
    path(
        'password-reset-complete/',
        auth_views.PasswordResetCompleteView.as_view(
            template_name='password_reset_complete.html',
        ),
        name='password_reset_complete'
    ),
]

ostrk/cart/urls.py
from django.urls import path

from cart import views

app_name = 'cart'

urlpatterns = [
    path('add/<product_id>/', views.add_to_cart, name='add_to_cart'),
    path('remove/<product_id>/', views.remove_from_cart, name='remove_from_cart'),
    path('list/', views.show_cart, name='show_cart'),
]

ostrk/orders/urls.py
from django.urls import path

from orders import views

app_name = "orders"

urlpatterns = [
    path('create', views.create_order, name='create_order'),
    path('list', views.user_orders, name='user_orders'),
    path('checkout/<int:order_id>', views.checkout, name='checkout'),
    path('fake-payment/<int:order_id>', views.fake_payment, name='pay_order')
]

ostrk/ostrk/urls.py
from django.contrib import admin
from django.urls import path, include
from women import views
from women.views import page_not_found

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('women.urls')),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('cart/', include('cart.urls', namespace='cart')),
    path('orders/', include('orders.urls', namespace='orders')),
]

handler404 = page_not_found

ostrk/women/urls.py
from django.conf.urls.static import static
from django.urls import path

from ostrk import settings
from . import views

app_name = 'women'

urlpatterns = [
    path('', views.index, name='index'),
    path('cats/<int:cat_id>', views.categories, name='cats'),
    path('about/', views.about, name='about'),
    path('category/<slug:slug>/', views.category, name='category'),
    path('<slug:slug>', views.product_detail, name='product_detail'),
    path('filter/<slug:slug>/', views.filter_by_category, name='filter_by_category'),
    path('favorites/', views.favorites, name='favorites'),
    path('add/favorites/<int:product_id>/', views.add_to_favorites, name='add_to_favorites'),
    path('remove/favorites/<int:product_id>/', views.remove_from_favorites, name='remove_from_favorites'),
    path('search/', views.search, name='search'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

ostrk/templates/base.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{{ title }}</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
</head>
<body style="height: 2000px">
<nav class="navbar sticky-top navbar-expand-lg bg-body-tertiary">
    <div class="container-fluid">
        <div class="container">
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse"
                    data-bs-target="#navbarSupportedContent"
                    aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Переключатель навигации">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                    <li class="nav-item">
                        {% if request.user.is_authenticated %}
                        <b class="text-primary">{{ cart_count }}</b>
                        {% endif %}
                        <a href="{% url 'cart:show_cart' %}" class="text-primary mt-2 me-2">
                            <svg xmlns="http://www.w3.org/2000/svg" width="32" height="32" fill=".text-dark"
                                 class="bi bi-bag-plus" viewBox="0 0 16 16">
                                <path fill-rule="evenodd"
                                      d="M8 7.5a.5.5 0 0 1 .5.5v1.5H10a.5.5 0 0 1 0 1H8.5V12a.5.5 0 0 1-1 0v-1.5H6a.5.5 0 0 1 0-1h1.5V8a.5.5 0 0 1 .5-.5z"/>
                                <path d="M8 1a2.5 2.5 0 0 1 2.5 2.5V4h-5v-.5A2.5 2.5 0 0 1 8 1zm3.5 3v-.5a3.5 3.5 0 1 0-7 0V4H1v10a2 2 0 0 0 2 2h10a2 2 0 0 0 2-2V4h-3.5zM2 5h12v9a1 1 0 0 1-1 1H3a1 1 0 0 1-1-1V5z"/>
                            </svg>
                        </a>
                    </li>
                    <li class="nav-item">
                        {% if request.user.is_authenticated %}
                        <b class="text-primary">{{ request.user.get_likes_count}}</b>
                        {% endif %}
                        <a href="{% url 'women:favorites' %}" class="text-primary mt-2 me-2">
                            <svg xmlns="http://www.w3.org/2000/svg" width="32" height="32" fill=".text-dark"
                                 class="bi bi-bag-heart" viewBox="0 0 16 16">
                                <path fill-rule="evenodd"
                                      d="M10.5 3.5a2.5 2.5 0 0 0-5 0V4h5v-.5Zm1 0V4H15v10a2 2 0 0 1-2 2H3a2 2 0 0 1-2-2V4h3.5v-.5a3.5 3.5 0 1 1 7 0ZM14 14V5H2v9a1 1 0 0 0 1 1h10a1 1 0 0 0 1-1ZM8 7.993c1.664-1.711 5.825 1.283 0 5.132-5.825-3.85-1.664-6.843 0-5.132Z"/>
                            </svg>
                        </a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link active" aria-current="page" href="/">Главная</a>
                    </li>
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown"
                           aria-expanded="false">
                            Каталог
                        </a>
                        <ul class="dropdown-menu">
                            {% for category in catalog %}
                            <li><a class="dropdown-item" href="{{ category.get_absolute_url }}">{{ category.title }}</a>
                            </li>
                            <hr class="dropdown-divider">
                            {% endfor %}
                    </li>
                </ul>
                </ul>
                <form class="d-flex" role="search">
                    <input class="form-control me-2" type="search" placeholder="Поиск" aria-label="Поиск">
                </form>
                {% if request.user.is_authenticated %}
                <!-- user profile dropdown -->
                <div class="dropdown text-end">
                    <a href="#"
                       class="btn btn-primary text-white me-4 d-block link-dark text-decoration-none dropdown-toggle"
                       id="dropdownUser1" data-bs-toggle="dropdown" aria-expanded="false">Профиль</a>
                    <ul class="dropdown-menu" aria-labelledby="dropdownUser1">
                        <li><a href="{% url 'cart:show_cart' %}" <a class="dropdown-item">Корзина</a></li>
                        <li><a href="{% url 'women:favorites' %}" <a class="dropdown-item">Избранные</a></li>
                        <li><a href="{% url 'orders:user_orders' %}" <a class="dropdown-item">Заказы</a></li>
                        <li><a class="dropdown-item" href="{% url 'accounts:edit_profile' %}">Изм. профиль</a></li>
                        <li><a class="dropdown-item text-danger" href="{% url 'accounts:user_logout' %}">Выход</a>
                        </li>
                    </ul>
                </div>
                {% else %}
                <!-- login, sign-up btn -->
                <div class="text-end">
                    <a href="{% url 'accounts:user_login' %}" class="btn btn-outline-primary">Вход</a>
                    <a href="{% url 'accounts:user_register' %}" class="btn btn-primary">Регистрация</a>
                </div>
                {% endif %}
            </div>
        </div>
    </div>
</nav>
<main class="container">
    <div class="row mt-3">
        <!-- messages -->
        {% if messages %}
        {% for message in messages %}
        <div class="alert alert-{{ message.tags }}">{{ message }}</div>
        {% endfor %}
        {% endif %}
        <!-- content -->
        {% block content %}{% endblock %}
    </div>
</main>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
</body>
</html>